// Generated by Haxe 4.3.4
#include <hxcpp.h>

#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_haxe_iterators_ArrayIterator
#include <haxe/iterators/ArrayIterator.h>
#endif
#ifndef INCLUDED_haxe_Int64Helper
#include <haxe/Int64Helper.h>
#endif
#ifndef INCLUDED_discord_GameSDK
#include <discord/GameSDK.h>
#endif
#ifndef INCLUDED_discord__GameSDK_NativeString_Impl_
#include <discord/_GameSDK/NativeString_Impl_.h>
#endif
#ifndef INCLUDED__Test_Test_Fields_
#include <_Test/Test_Fields_.h>
#endif
#ifndef INCLUDED_Sys
#include <Sys.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_Date
#include <Date.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
::hx::RegisterResources( ::hx::GetResources() );
::haxe::Log_obj::__register();
::haxe::iterators::ArrayIterator_obj::__register();
::haxe::Int64Helper_obj::__register();
::discord::GameSDK_obj::__register();
::discord::_GameSDK::NativeString_Impl__obj::__register();
::_Test::Test_Fields__obj::__register();
::Sys_obj::__register();
::StringTools_obj::__register();
::Std_obj::__register();
::Date_obj::__register();
::haxe::Log_obj::__boot();
}

