// Generated by Haxe 4.3.4
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"?",
"C:\\HaxeToolkit\\haxe\\std/StringTools.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Date.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Std.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Sys.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/Log.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/Int64Helper.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/iterators/ArrayIterator.hx",
"Test.hx",
"discord/GameSDK.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"C:\\Users\\Home\\Documents\\GitHub\\projects\\hxdiscord_gamesdk\\?",
"C:\\HaxeToolkit\\haxe\\std\\StringTools.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Date.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Std.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Sys.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\Log.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\Int64Helper.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\iterators\\ArrayIterator.hx",
"C:\\Users\\Home\\Documents\\GitHub\\projects\\hxdiscord_gamesdk\\Test.hx",
"C:\\Users\\Home\\Documents\\GitHub\\projects\\hxdiscord_gamesdk\\discord\\GameSDK.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Date",
"Std",
"StringTools",
"Sys",
"_Test.Test_Fields_",
"discord._GameSDK.NativeString_Impl_",
"discord.GameSDK",
"haxe.Int64Helper",
"haxe.Log",
"haxe.iterators.ArrayIterator",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
