// Generated by Haxe 4.3.4
#ifndef INCLUDED_discord__GameSDK_NativeString_Impl_
#define INCLUDED_discord__GameSDK_NativeString_Impl_

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(discord,_GameSDK,NativeString_Impl_)

namespace discord{
namespace _GameSDK{


class HXCPP_CLASS_ATTRIBUTES NativeString_Impl__obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef NativeString_Impl__obj OBJ_;
		NativeString_Impl__obj();

	public:
		enum { _hx_ClassId = 0x580f8bbd };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="discord._GameSDK.NativeString_Impl_")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"discord._GameSDK.NativeString_Impl_"); }

		inline static ::hx::ObjectPtr< NativeString_Impl__obj > __new() {
			::hx::ObjectPtr< NativeString_Impl__obj > __this = new NativeString_Impl__obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< NativeString_Impl__obj > __alloc(::hx::Ctx *_hx_ctx) {
			NativeString_Impl__obj *__this = (NativeString_Impl__obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(NativeString_Impl__obj), false, "discord._GameSDK.NativeString_Impl_"));
			*(void **)__this = NativeString_Impl__obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~NativeString_Impl__obj();

		HX_DO_RTTI_ALL;
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("NativeString_Impl_",88,18,12,4e); }

		static const char* _new(::String s);

};

} // end namespace discord
} // end namespace _GameSDK

#endif /* INCLUDED_discord__GameSDK_NativeString_Impl_ */ 
