// Generated by Haxe 4.3.4
#include <hxcpp.h>

#ifndef INCLUDED_discord__GameSDK_NativeString_Impl_
#include <discord/_GameSDK/NativeString_Impl_.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_e5a0cfff6dd3b6ae_20__new,"discord._GameSDK.NativeString_Impl_","_new",0x8c1d23e4,"discord._GameSDK.NativeString_Impl_._new","discord/GameSDK.hx",20,0x5a9e60b9)
namespace discord{
namespace _GameSDK{

void NativeString_Impl__obj::__construct() { }

Dynamic NativeString_Impl__obj::__CreateEmpty() { return new NativeString_Impl__obj; }

void *NativeString_Impl__obj::_hx_vtable = 0;

Dynamic NativeString_Impl__obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< NativeString_Impl__obj > _hx_result = new NativeString_Impl__obj();
	_hx_result->__construct();
	return _hx_result;
}

bool NativeString_Impl__obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x580f8bbd;
}

const char* NativeString_Impl__obj::_new(::String s){
            	HX_STACKFRAME(&_hx_pos_e5a0cfff6dd3b6ae_20__new)
HXDLIN(  20)		return s.utf8_str();
            	}



NativeString_Impl__obj::NativeString_Impl__obj()
{
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *NativeString_Impl__obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *NativeString_Impl__obj_sStaticStorageInfo = 0;
#endif

::hx::Class NativeString_Impl__obj::__mClass;

void NativeString_Impl__obj::__register()
{
	NativeString_Impl__obj _hx_dummy;
	NativeString_Impl__obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("discord._GameSDK.NativeString_Impl_",cb,e0,f6,4e);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< NativeString_Impl__obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = NativeString_Impl__obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = NativeString_Impl__obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace discord
} // end namespace _GameSDK
